In [2]:
import pandas as pd

$$odds = \frac{p}{1-p}$$

In [ ]:
probabilities = [0.1, 0.3, 0.5, 0.7, 0.9]

odds_table = pd.DataFrame({
    "probability": probabilities
})


p = odds_table["probability"] 

odds_table["odds"] = p/ (1-p) 

odds_table

# Positive Relationship

# Negative Relationship

   probability      odds
0          0.1  0.111111
1          0.3  0.428571
2          0.5  1.000000
3          0.7  2.333333
4          0.9  9.000000

In [ ]:
from math import log

np.float64(0.1)

In [15]:
log(p[0]/(1-p[0]))

-2.197224577336219

In [18]:
odds_table['log_ods'] = [log(i/(1-i)) for i in list(p)]

odds_table

   probability      odds   log_ods
0          0.1  0.111111 -2.197225
1          0.3  0.428571 -0.847298
2          0.5  1.000000  0.000000
3          0.7  2.333333  0.847298
4          0.9  9.000000  2.197225

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (confusion_matrix, 
                             accuracy_score, 
                             precision_score, 
                             recall_score, 
                             f1_score)

df = pd.read_csv("https://raw.githubusercontent.com/hovhannisyan91/data_analytics_with_python/refs/heads/main/data/regression/logistic_regression/synthetic_churn_data.csv")
print(f"Dataset shape: {df.shape}")
df.head()

Dataset shape: (1000, 6)

,tenure,monthly_charges,support_calls,contract_type,churn,education_level
0,29,46.867736,6,0,0,High School
1,15,74.163421,6,0,0,Bachelor
2,8,83.347822,3,1,0,Master
3,21,45.788769,2,0,0,High School
4,19,33.935607,7,0,1,Master

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   tenure           1000 non-null   int64
 1   monthly_charges  1000 non-null   float64
 2   support_calls    1000 non-null   int64
 3   contract_type    1000 non-null   int64
 4   churn            1000 non-null   int64
 5   education_level  1000 non-null   str
dtypes: float64(1), int64(4), str(1)
memory usage: 53.8 KB

In [3]:
df['churn'].value_counts(normalize=True)

churn
0    0.633
1    0.367
Name: proportion, dtype: float64

In [4]:
df['churn'].value_counts(normalize=False)

churn
0    633
1    367
Name: count, dtype: int64

In [9]:
df[['churn', 'contract_type']].value_counts(normalize=True)

churn  contract_type
0      1                0.347
       0                0.286
1      0                0.235
       1                0.132
Name: proportion, dtype: float64

In [5]:
churn_rate_by_contract = df.groupby('contract_type')['churn'].mean().reset_index()
import plotly.express as px
fig = px.bar(churn_rate_by_contract, x='contract_type', y='churn', title='Churn Rate by Contract Type')
fig.update_layout(
    xaxis_title='Contract Type (0 = Prepaid, 1 = Postpaid',
    yaxis_title='Churn Rate',
    template='plotly_white'
)   
fig.show()

In [11]:
churn_rate_by_education = df.groupby('education_level')['churn'].mean().reset_index()
import plotly.express as px
fig = px.bar(churn_rate_by_education, x='education_level', y='churn', title='Churn Rate by Education Level')
fig.update_layout(
    xaxis_title='Education Level',
    yaxis_title='Churn Rate',
    template='plotly_white'
)   
fig.show()

In [13]:
X = df.drop(columns=["churn"])
y = df["churn"]

In [17]:
education_order = ["High School", "Bachelor", "Master", "PhD"]

df["education_level"] = pd.Categorical(
    df["education_level"],
    categories=education_order,
    ordered=True
)

education_dummies = pd.get_dummies(
    df["education_level"],
    prefix="education",
    drop_first=True,
    dtype=int
)

education_dummies.head()

   education_Bachelor  education_Master  education_PhD
0                   0                 0              0
1                   1                 0              0
2                   0                 1              0
3                   0                 0              0
4                   0                 1              0

In [18]:
X

     tenure  monthly_charges  support_calls  contract_type education_level
0        29        46.867736              6              0     High School
1        15        74.163421              6              0        Bachelor
2         8        83.347822              3              1          Master
3        21        45.788769              2              0     High School
4        19        33.935607              7              0          Master
..      ...              ...            ...            ...             ...
995      30        20.321826              6              0     High School
996      23        81.958934              3              1          Master
997      32        55.549301              8              0             PhD
998      17        99.419733              4              0          Master
999      17        29.299064              3              0        Bachelor

[1000 rows x 5 columns]

In [22]:
X_encoded = pd.concat([X.drop(columns='education_level'),education_dummies],axis=1)

X_encoded.head()

,tenure,monthly_charges,support_calls,contract_type,education_Bachelor,education_Master,education_PhD
0,29,46.867736,6,0,0,0,0
1,15,74.163421,6,0,1,0,0
2,8,83.347822,3,1,0,1,0
3,21,45.788769,2,0,0,0,0
4,19,33.935607,7,0,0,1,0

In [24]:
X = X_encoded
del X_encoded

In [25]:
def test():
    return ('X_train', 'X_test', 'y_train', 'y_test')

In [27]:
x_1, x2, x3, x4 = test()

x_1

'X_train'

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,
                                                    test_size=0.2,
                                                    random_state=42, 
                                                    stratify=y)

In [36]:
train_size = len(X_train)
test_size = len(X_test)

train_churn_rate = y_train.mean()
test_churn_rate = y_test.mean()

print("Training rows:", train_size)
print("Test rows:", test_size)
print("Training churn rate:", round(train_churn_rate, 3))
print("Test churn rate:", round(test_churn_rate, 3))

Training rows: 800
Test rows: 200
Training churn rate: 0.368
Test churn rate: 0.365

In [38]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [55]:
probs = model.predict_proba(X_test)

# [1-p, p]
probs = probs[:,1]

In [56]:
threshold = 0.5
preds = (probs >= threshold).astype(int)
preds[:5]

array([0, 0, 0, 1, 0])

In [59]:
prediction_results = X_test.copy()

prediction_results['actual_churn']  = y_test.values
prediction_results['prediction_probs']  = probs
prediction_results['prediction_churn']  = preds

In [60]:
prediction_results.head()

,tenure,monthly_charges,support_calls,contract_type,education_Bachelor,education_Master,education_PhD,actual_churn,prediction_probs,prediction_churn
361,34,55.062693,2,1,0,0,0,0,0.016812,0
5,23,103.493024,4,0,0,0,1,0,0.417270,0
692,25,75.778342,5,0,0,1,0,1,0.474894,0
708,6,112.717782,5,1,0,1,0,0,0.615989,1
841,26,67.601813,7,1,0,0,1,0,0.320633,0

**Outcome	Meaning**
- **True Positive**	Customer churned and model predicted churn
- **False Positive**	Customer did not churn but model predicted churn
- **False Negative**	Customer churned but model missed it
- **True Negative**	Customer did not churn and model predicted no churn

In [74]:
prediction_results[['actual_churn','prediction_churn']].value_counts()

actual_churn  prediction_churn
0             0                   103
1             1                    50
0             1                    24
1             0                    23
Name: count, dtype: int64

In [ ]:
(103+50)/200

0.684931506849315

In [ ]:
cm = confusion_matrix(y_test, preds)

tn, fp, fn, tp = cm.ravel()

array([[103,  24],
       [ 23,  50]])

In [90]:
accuracy = accuracy_score(y_test,preds)
precission = precision_score(y_test,preds)
print("precision_score:", precission)

tp/(tp+fp)

precision_score: 0.6756756756756757

np.float64(0.6756756756756757)

In [86]:
recall = recall_score(y_test,preds)
print('recall:', recall)
50/(50+23)

recall: 0.684931506849315

0.684931506849315

In [69]:
cm = confusion_matrix(y_test,preds,normalize='all')
cm

array([[0.515, 0.12 ],
       [0.115, 0.25 ]])

In [70]:
cm = confusion_matrix(y_test,preds,normalize='true')
cm

array([[0.81102362, 0.18897638],
       [0.31506849, 0.68493151]])

In [94]:
retention_cost = 10
retention_benefit = 50 #COHORT Analysis

revenue_from_saved_customers = tp * (retention_benefit - retention_cost)
cost_from_unnecessary_contacts = fp * retention_cost

net_profit = revenue_from_saved_customers - cost_from_unnecessary_contacts

print("Revenue from saved customers:", revenue_from_saved_customers)
print("Cost from unnecessary contacts:", cost_from_unnecessary_contacts)
print("Net profit:", net_profit)

Revenue from saved customers: 2000
Cost from unnecessary contacts: 240
Net profit: 1760

In [106]:
prediction_results.sort_values(by='prediction_probs',ascending=False).head(50)

,tenure,monthly_charges,support_calls,contract_type,education_Bachelor,education_Master,education_PhD,actual_churn,prediction_probs,prediction_churn
120,2,43.295947,9,0,0,1,0,1,0.942005,1
456,9,116.941232,7,0,0,0,1,1,0.918465,1
291,20,88.049930,9,0,0,0,1,0,0.914075,1
409,9,85.032569,8,0,0,0,1,1,0.912285,1
59,16,69.549132,9,0,0,0,1,1,0.901073,1
103,9,102.891547,7,0,0,0,1,1,0.894338,1
42,17,76.640464,8,0,1,0,0,1,0.888740,1
869,1,28.479202,8,0,0,1,0,1,0.877842,1
638,29,102.261432,8,0,0,1,0,1,0.872714,1
45,6,113.682974,8,1,0,0,1,0,0.865496,1
493,6,113.387502,8,1,0,0,1,1,0.864794,1
319,13,82.622032,7,0,0,1,0,0,0.863050,1
368,4,100.058670,6,0,0,0,1,1,0.856348,1
378,12,90.906052,7,0,0,0,1,0,0.848918,1
994,10,89.561815,9,1,0,0,1,0,0.848023,1
221,18,85.845183,7,0,0,1,0,0,0.836170,1
591,17,109.803055,6,0,0,1,0,1,0.832485,1
11,22,111.429881,7,0,0,0,1,1,0.830731,1
418,12,94.270652,6,0,0,1,0,1,0.826895,1
712,11,119.248350,5,0,0,1,0,1,0.826048,1
760,1,112.275719,7,1,0,0,1,1,0.823488,1
483,28,106.827128,7,0,0,1,0,1,0.818170,1
539,2,24.821204,8,0,0,0,1,1,0.818156,1
180,3,59.624202,9,1,0,0,1,1,0.817146,1
631,4,61.102847,9,1,0,0,1,0,0.813349,1
878,10,54.970323,7,0,0,1,0,1,0.809099,1
222,2,105.058173,7,1,0,0,1,1,0.792167,1
20,25,33.688563,9,0,0,1,0,0,0.789282,1
33,9,93.803362,8,1,0,0,1,1,0.784386,1
245,30,118.118618,7,0,0,0,1,1,0.783232,1
859,5,109.511774,7,1,0,0,1,1,0.779505,1
47,29,41.494038,9,0,0,1,0,1,0.778725,1
421,25,57.103876,8,0,0,1,0,0,0.773402,1
196,16,106.212762,8,1,0,0,1,0,0.760762,1
252,35,96.102790,8,0,0,0,1,0,0.755769,1
752,10,37.352451,7,0,0,1,0,1,0.747579,1
980,11,115.807348,7,1,0,0,1,1,0.742527,1
738,4,119.215801,4,0,0,0,1,1,0.738140,1
1,15,74.163421,6,0,1,0,0,0,0.730943,1
155,19,28.941100,8,0,1,0,0,0,0.730458,1
115,13,99.072316,7,1,0,1,0,1,0.720440,1
627,31,108.420646,9,1,0,0,1,1,0.719470,1
532,29,41.567515,9,0,0,0,1,0,0.715288,1
791,4,89.503523,7,1,0,0,1,1,0.713208,1
929,1,45.224102,6,0,0,0,1,1,0.697532,1
226,4,89.747146,4,0,0,1,0,1,0.684676,1
916,30,63.940499,8,0,0,0,1,1,0.679557,1
92,27,111.548830,6,0,0,0,1,1,0.678624,1
599,34,45.677657,9,0,0,0,1,0,0.674453,1
725,11,50.312836,6,0,0,1,0,0,0.673657,1

In [108]:

model.coef_[0]
np.exp(model.coef_[0])

array([0.94621391, 1.02055269, 1.76711819, 0.29261887, 1.13068091,
       1.11880244, 0.79749422])

In [110]:
coef_df = pd.DataFrame({
    "feature": X.columns,
    "beta": model.coef_[0],
    "exp_beta": np.exp(model.coef_[0])
})

coef_df = coef_df.sort_values("exp_beta", ascending=False)

coef_df

              feature      beta  exp_beta
2       support_calls  0.569350  1.767118
4  education_Bachelor  0.122820  1.130681
5    education_Master  0.112259  1.118802
1     monthly_charges  0.020344  1.020553
0              tenure -0.055287  0.946214
6       education_PhD -0.226281  0.797494
3       contract_type -1.228884  0.292619